### ISSUE TITLE
AttributeError: 'MBInfo' object has no attribute 'diff'

### ISSUE THREAD

**Issue by white-gecko** [redbmk/bin#5]
git-diff-search fails with:

```
=== Gathering commit tree
=== Finding branching/merging commits
=== Rough search following only branch/merge commits
Setze Branch 'tmp' neu
c389cb7 (      547)  
Traceback (most recent call last):
  File "git-diff-search.py", line 205, in <module>
    status.follow_commits(status.commits[status.first[:7]],jump='knots',**kw)
  File "git-diff-search.py", line 163, in follow_commits
    cur = metric(node)
  File "git-diff-search.py", line 115, in fastdiff
    if c.diff is not None:
AttributeError: 'MBInfo' object has no attribute 'diff'
```

**Comment by white-gecko** [comment]
@burnpanck I also ping you, as the python implementation is coming from you.

**Comment by burnpanck** [comment]
Huh, that was a long time ago, took me some time to even recognise what this was! I was even using Enthought's [`traits`](https://github.com/enthought/traits) back then... These days, I would probably use either plain python [`dataclasses`](https://docs.python.org/3/library/dataclasses.html) or potentially [`attrs`](https://www.attrs.org/en/stable/).

In any case, I have no intention to spend much time on this at this point. I vaguely remember that the script simplifies the git commit tree to a graph where branch and merge commits are considered nodes, and sequences of regular commits are edges. It then first selects the "best" edge, and bisects that edge to find the best commit. The failure seems to come from the edge selection part.

Apparently, each commit is represented using a `Commit` object, while the graph is encoded in `MBInfo` objects. It seems that at some point, the latter is accidentally fed into the metric function, while it should have been the associated former instead. Doing a detailed type analysis might bring clarity (maybe with the help of [type annotations](https://docs.python.org/3/library/typing.html) and a good static type checker, e.g. in your editor or [mypy](https://mypy.readthedocs.io/en/stable/)). Alternatively, you could try to fix it using
```python
if isinstance(c, MBInfo):
    c = c.commit
```
although [one should never fix something one doesn't understand](https://therealgriff.medium.com/if-you-dont-understand-a-problem-you-re-not-allowed-to-fix-it-af6b8054606c), and I don't fully understand the exact issue here.

**Comment by white-gecko** [comment]
Thank you very much for the reply. I've now solved my issue with a simple loop, as for my use case it is not important to analyze the complete graph. Further, I only had to compare a single file and not a complete tree.

Here my line for the reference.

    for i in $( git log --oneline path/in/the/repo/file.py | awk '{print $1}' ); do git show --raw $i | grep path/in/the/repo/file.py | awk '{print $4}' | xargs git show --raw | diff -w path/to/the/file/i/want/to/compare/file.py - | grep "^<" | wc -l ; echo $i ; done

(The `grep "^<"` can be replaced with `grep "^>"` of cause.)
There should be room for improvements, maybe it can be simplified or provide better output in some way (additions and deletions in one run, showing the commit message and date, …)
